spring:
 data:
  mongodb:
   uri: mongodb://localhost:27017/ipldata?readPreference=primary&appname=MongoDB%20Compass&ssl=false
    batch:    job:      enabled: false
      
server:  servlet:    context-path: /iplstat
    
app:
 info: 
  desc: 
     Spring Boot with MongoDB and Rest API application
  version: 
     1.0.0