spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/lwl
     username: dbuser
     password: dbuser@123
     initialization-mode: always
  jpa:    hibernate:      ddl-auto: none    show-sql: true   

server:
  servlet:
    context-path: /todo